---
- name: Deploy OpenTelemetry Collector on Windows
  hosts: all
  gather_facts: no

  tasks:
    - name: Create folder for Otel Collector
      win_file:
        path: C:\otel
        state: directory
        
    - name: Upload config.yaml
      win_copy:
        dest: C:\otel\config.yaml
        content: |
          receivers:
            hostmetrics:
              collection_interval: 10s
              scrapers:
                cpu:
                memory:

          exporters:
            logging:
              loglevel: debug

          service:
            pipelines:
              metrics:
                receivers: [hostmetrics]
                exporters: [logging]

    - name: Install OpenTelemetry as a service
      ansible.windows.win_service:
        name: opentelemetry
        path: C:\otel\otelcol-contrib.exe
        display_name: Open Telemetry Collector
        description: An Otel service

    - name: Start the service
      win_service:
        name: otelcol
        start_mode: auto
        state: started
